// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrLOmWrErdL1gu9VuoVLuZM3KCLel6oCc',
    appId: '1:864959251314:web:c60ae1633ed65a438153eb',
    messagingSenderId: '864959251314',
    projectId: 'ecommerceapp-45684',
    authDomain: 'ecommerceapp-45684.firebaseapp.com',
    storageBucket: 'ecommerceapp-45684.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALeTm2yerevqE7NruemCZosHc4rpyStYQ',
    appId: '1:864959251314:android:dad6f342e07980d78153eb',
    messagingSenderId: '864959251314',
    projectId: 'ecommerceapp-45684',
    storageBucket: 'ecommerceapp-45684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDzj9VFLycLadGTc74jcRWw6tTE6U91-I',
    appId: '1:864959251314:ios:24bd305402649f738153eb',
    messagingSenderId: '864959251314',
    projectId: 'ecommerceapp-45684',
    storageBucket: 'ecommerceapp-45684.appspot.com',
    androidClientId: '864959251314-fg3bi7sm441i883fckk8q7cerdbjj26f.apps.googleusercontent.com',
    iosClientId: '864959251314-kpifqtd13tb18eor37sei0qjvjuis1hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.viStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDzj9VFLycLadGTc74jcRWw6tTE6U91-I',
    appId: '1:864959251314:ios:a1f2850f0f0c1f2e8153eb',
    messagingSenderId: '864959251314',
    projectId: 'ecommerceapp-45684',
    storageBucket: 'ecommerceapp-45684.appspot.com',
    androidClientId: '864959251314-fg3bi7sm441i883fckk8q7cerdbjj26f.apps.googleusercontent.com',
    iosClientId: '864959251314-anf4v2dqrhgddki5ql47so0cmepvubqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.viStore.RunnerTests',
  );
}
